---
- name: Unarchive after downloaded heketi server tar
  unarchive:
    src: https://github.com/heketi/heketi/releases/download/v9.0.0/heketi-v9.0.0.linux.amd64.tar.gz
    dest: /tmp
    remote_src: yes

- name: Move Heketi to /usr/bin
  command: mv /tmp/heketi/heketi /tmp/heketi/heketi-cli /usr/bin