---
# - name: Deploy ssl, that is k8s dashboad needed
#   hosts: k8s harbor gluster1
#   tasks:
#     - copy: 
#         src: "{{ item }}"
#         dest: "/certs/"
#       with_items:
#         - "./certs/fengdu.cloud.pem"
#         - "./certs/fengdu.cloud.privatekey.pem"

- name: Deploy ssl
  hosts: jenkins
  tasks:
    - copy: 
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
      with_items:
        - "{{ ssl_cert }}"
        - "{{ ssl_key }}"

# - name: Deploy ssl, that is k8s dashboad needed
#   hosts: harbor
#   tasks:
#     - copy: 
#         src: "{{ item }}"
#         dest: "/certs/"
#       with_items:
#         - "{{ cert }}"
#         - "{{ cert_key }}"

# - name: Deploy ssl to server 
#   hosts: dns
#   tasks:
#     - copy: 
#         src: "files/certs/fengdu.cloud.pem"
#         dest: "/etc/ssl/certs"
#     - copy: 
#         src: "files/certs/fengdu.cloud.privatekey.pem"
#         dest: "/etc/ssl/private"
#     - command: update-ca-certificates
