- name: Disable systemd-resolved on dns
  systemd:
    name: systemd-resolved.service
    enabled: no
    state: stopped

- name: Install coredns on dns
  import_role:
    name: cloudalchemy.coredns
  vars:
    coredns_config_file: 'templates/Corefile.j2'