---
- name: Install Docker CE.
  apt:
    name:
      - 'docker-ce={{ docker_version }}'
    state: present

- name: Docker daemon.json config
  copy:
      src: files/daemon.json
      dest: /etc/docker/daemon.json
  register: docker_daemon_config_file

- name: Creates Docker service directory
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory
    recurse: yes

- systemd:
    state: restarted
    daemon_reload: yes
    name: docker
  when: docker_daemon_config_file is changed