---
- name: Ensure dependencies are installed.
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    state: present

- name: Add Docker apt key.
  apt_key:
    url: http://mirrors.aliyun.com/docker-ce/linux/ubuntu/gpg
    state: present
  ignore_errors: "{{ docker_apt_ignore_key_error }}"

- name: Add Docker apt repository.
  apt_repository:
    repo: "{{ docker_apt_repository }}"
    state: present
    update_cache: true

